### ISSUE TITLE
Web Application Not Loading

### ISSUE THREAD

**Issue by CalebWeather** [hydroframe/SandTank#90] opened 2024-07-15 18:47 UTC
I have several students that have not been able to open the website application since about 11 pm EDT last night (07/14). I have tried to open it myself on Google Chrome, Microsoft Edge, and Mozilla Firefox for the last several hours to no avail. All the site does is stay in a constant loop of trying to load. This has been tested on Windows, Linux, and Apple machines, as well.

- javascript is enabled
- tested disabling extensions
- cleared cache
- internet connection is great

Attached is a screenshot and video of what myself and my students are getting (I am a TA and we need this for a lab assignment). Any help is appreciated!

![SandTank_Loading_Issue](https://github.com/user-attachments/assets/07c2981c-f509-4720-80ae-c0b454acce9c)

https://github.com/user-attachments/assets/eddb0802-00a0-414f-91c9-1f617b8228fa

**Comment by welytle** [comment] 2024-07-15 20:16
@CalebWeather Thank you for the detailed description of the problem and sorry for the trouble. We've fixed the service and it should be back up and running. We are still conducting and RCA and will hopefully have a more robust fix in place soon.

**Comment by welytle** [comment] 2024-08-12 18:24
The RCA reveled that this outage was do to a memory issue on the server.  Space has been made available for this application to run. I'm going to close the issue now since the issue is resolved.

**Closed as completed by welytle** 2024-08-12 18:24 UTC
